### PR TITLE
Rebases #983 (Add decorator to allow specification of the schema type name #983)

### PR DESCRIPTION
**Pull request by mothershipper**
See #983 and #1596 

TL;DR; cherry-picked the commits onto the latest master branch to resolve conflicts in the PR. Original author info should be maintained on the commits.

### CODE REVIEW

**Comment by mothershipper** [comment]
Just double checked and it seems like the [docs PR](https://github.com/nestjs/docs.nestjs.com/pull/1533) also needs a rebasing -- @kamilmysliwiec I'm a bit tied up this morning, but happy to get to that either late today or tomorrow. Could we perhaps merge this (when approved) as a kind of forcing-function to get the docs PR pushed through as well?

**Comment by RobbyUitbeijerse** [comment]
hey there! Was just looking for this functionality, any chance this is ready to be merged? If there's something I can help with let me know.

**Comment by GuilhermeGuitte** [comment]
Hey there! Any news regarding this feature?

**Comment by GuilhermeGuitte** [comment]
@kamilmysliwiec Do you think this feature is something you are looking forward to integrate on this package? Thanks!

**Comment by CSenshi** [comment]
@kamilmysliwiec any plans on merging this PR in the near future?

**Review by MarshallCat94 — APPROVED** [review]

**Review by luskin — APPROVED** [review]

**Comment by wespen** [comment]
Any updates on when will this PR be merged?

**Comment by nikhilro** [comment]
Gentle bump, would appreciate this too.

**Comment by giancarlo-dm** [comment]
I don't want to sound harsh, but I need this too and and this this feature was requests multiple times already and it goes as back as [2021](https://github.com/nestjs/swagger/issues/1638) and we are 2024 already. Why is this taking so long?

**Comment by ThatsARapp** [comment]
@kamilmysliwiec Anything in particular holding this up? I would love to have this right about now. Happy to work on any changes if that will get the ball rolling again.

**Review by sleeyax — APPROVED** [review]
LGTM!

**Pull request merged**
