### PR TITLE
Fix schema creation for enum ApiParam

### PR DESCRIPTION
**Pull request by mateusppereira**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

### CODE REVIEW

**Comment by mateusppereira** [comment]
solve #1479

**Review by gmcheco — APPROVED** [review]

**Review by mamane19 — APPROVED** [review]

**Review by mamane19 — APPROVED** [review]

**Comment by silte** [comment]
Could this be merged?

**Comment by calebpitan** [comment]
Would really love for this to be merged

**Comment by okonon** [comment]
I am also interested in this

**Comment by mateusppereira** [comment]
@kamilmysliwiec @flamewow can you check this PR please?

**Review by rubiin — APPROVED** [review]

**Review by faithfulojebiyi — APPROVED** [review]

**Comment by adamnyberg** [comment]
Please merge 🙏🏻 this is very frustrating

**Review by micalevisk — APPROVED** [review]

**Comment by Mkohm** [comment]
It would be great to have this one merged!

**Review by Tony133 — APPROVED** [review]

**Comment by okonon** [comment]
@kamilmysliwiec would you be able to take a look and merge this PR ? thank you very much

**Comment by bawahakim** [comment]
Also need this, thanks!

**Comment by bawahakim** [comment]
@kamilmysliwiec Would also need this, thanks!

**Comment by joshgrift** [comment]
Anything I can do to help get this merged?

**Comment by rslowinski** [comment]
+1, can i somehow help movin forward with this PR?

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/swagger/pull/2734

**Pull request closed without merging**
