### PR TITLE
feat(): added decorator for exclude controller

### PR DESCRIPTION
**Pull request by Tony133**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Other... Please describe:
```

## What is the current behavior?

Issue Number: #1145 

## What is the new behavior?
Added decorator for exclude controller

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
This PR, added decorator for exclude controller

### CODE REVIEW

**Comment by Tony133** [comment]
to evaluate if the implementation is correct :-)

**Comment by kamilmysliwiec** [comment]
Can you please add appropriate tests that verify if this decorator truly works?

**Comment by Tony133** [comment]
@kamilmysliwiec, I added a test but I'm not sure I did it right as it gives me an error you can see on ci/circleci: unit_tests, in fact the test fails, as soon as I add the decorator `@ApiExcludeController (true)`. Then as I said in the message above I wasn't sure if I implemented it well.

I think the problem is in` api-exclude-controller.explorer.ts`this part here:

```prototype: Type<unknown>```



Do you have any ideas how to fix it?

P.s. I noticed that the tests for the `@ApiExcludeEndpoint` decorator are also missing.

**Comment by kamilmysliwiec** [comment]
The decorator's code is incorrect. You've tried applying a `MethodDecorator` to a class (and that should have a signature that matches the `ClassDecorator` interface)

**Comment by Tony133** [comment]
In this way it no longer gives the error but it does not convince me that much how I have implemented it 🤔

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/swagger/pull/1270

**Pull request closed without merging**
