### PR TITLE
feature(): add implicit class header decorators

### PR DESCRIPTION
**Pull request by iJimmyWei**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ x] Tests for the changes have been added (for bug fixes / features)
- [ x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Swagger currently does not permit using class decorators for headers. This means that, for example, any authenticated method that requires a header will need an implicit header method, and they will need it for **every** method within the controller.
Issue Number: https://github.com/nestjs/swagger/issues/287

## What is the new behavior?
Introduces a new decorator, known as `@ApiImplicitClassHeader` to allow usage of the header decorator on the controller level.

## Does this PR introduce a breaking change?
```
[ ] Yes
[ x] No
```

## Other information

### CODE REVIEW

**Comment by danvy** [comment]
Thank you. I'm interested in this PR.

**Comment by iJimmyWei** [comment]
Can anyone review this? @kamilmysliwiec

**Comment by styopdev** [comment]
I would love to have this as well

**Comment by kamilmysliwiec** [comment]
This feature has been added in 4.0.0 already. Hence, we can't merge your PR. Thanks for the contribution though!

**Pull request closed without merging**
