### PR TITLE
Support OpenAPI link objects

### PR DESCRIPTION
**Pull request by coyotte508**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Swagger link objects are not supported.

Issue Number: #1159

## What is the new behavior?

Swagger link objects are supported.

- `@ApiProperty` supports a new parameter `link` which contains a lazy function pointing to the linked type
- `@ApiDefaultGetter` was added to specify that a method of a controller is the default getter for a specific type. It is used together with `@ApiProperty({link: () => type])` to generate links
- `@ApiLink` was added to generate links that are more complicated than a direct getter

Here's an example:

```ts
class Human {
  @ApiProperty()
  id: string;

  @ApiProperty({ link: () => Human })
  @ApiPropertyOptional()
  spouseId?: string;

  @ApiProperty({ link: () => Human })
  parentIds: string[];
}

@Controller('')
class HumanController {
  @ApiDefaultGetter(Human, 'id')
  @Get(':id')
  @ApiOkResponse({
    type: Human,
    description: 'Human corresponding to `id`'
  })
  getHuman(@Param('id') id: string): Promise<Human> {
    const human = new Human();
    human.id = id;
    return Promise.resolve(human);
  }

  @Get(':id/children')
  @ApiLink({ from: Human, routeParam: 'id' })
  @ApiOkResponse({
    type: [Human],
    description: 'Children of human with id `id`'
  })
  getChildren(@Param('id') id: string): Promise<Human[]> {
    return Promise.resolve([]);
  }
}
```

links will be generated for both routes in the swagger document.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

I based this PR off the commit in #1169 . I can rewrite the PR without the changes from the commit from #1169 if needed.

### CODE REVIEW

**Comment by coyotte508** [comment]
That was the last forcepush - I added the doc

**Comment by coyotte508** [comment]
I'm thinking about a more generic design - the current design only allows to link to direct getters. 

Eg:

```ts
class User {
  @ApiProperty()
  id

  @ApiProperty({link: () => ProjectGet)
  projectId
}
```

But what if there are multiple projects per user, and user does not contain `projectIds`?

E.g.

```ts
class User {
  @ApiProperty()
  id
}

class Project {
  @ApiProperty()
  id

  // this is already handled by the PR
  @ApiProperty({link: () => User})
  userId
}

@Controller('users')
class UserController {
  @Get(':id')
  @ApiDefaultGetter(User, 'id')
  getOne(@Param('id') id: string) {...}

  // How to create this link ?
  @Get(':id/projects')
  getProjects(@Param('id') id: string) {...]
}

@Controller('projects')
class ProjectController {
  @Get(':id')
  @ApiDefaultGetter(User, 'id')
  getOne(@Param('id') id: string) {...}
}
```

I'm going to think it over and update the PR when I find a solution (or if someone has an idea)

**Comment by coyotte508** [comment]
I added an additional decorator: `@ApiLink` and updated the PR description.

**Comment by coyotte508** [comment]
Is there anything I can do (API changes, ...) to improve this PR?

**Comment by coyotte508** [comment]
Rebased & changed base on upcoming 8.0.0

**Comment by kiley-poole** [comment]
Any movement on this? How can I help get it over the line?

**Comment by vahidvdn** [comment]
Any update on this? 👀

**Comment by vahidvdn** [comment]
@coyotte508 Thanks for this amazing feature. Btw, your example is a bit confusing. Can you please provide another example for better understanding?

**Pull request merged**
