### PR TITLE
feat(@nest/swagger): multiple @ApiExtraModels on same method/controller

### PR DESCRIPTION
**Pull request by mo4islona**
## PR Checklist
Please check if your PR fulfills the following requirements:
```
[x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
[x] Tests for the changes have been added (for bug fixes / features)
[ ] Docs have been added / updated (for bug fixes / features)
```

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #1366

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/swagger/issues/1366 Thanks for reporting & creating a PR!

**Comment by mo4islona** [comment]
Hi there! 
Any chance to get it merged?

**Comment by kamilmysliwiec** [comment]
Can you please add a test for this?

**Comment by mo4islona** [comment]
@kamilmysliwiec done

**Comment by kamilmysliwiec** [comment]
LGTM

**Pull request merged**
