### PR TITLE
Added enum to ApiImplicitQuery to support enum type on SwaggerSpec

### PR DESCRIPTION
**Pull request by nartc**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Other... Please describe:
```
Enhancement to `@ApiImplicitQuery` decorator.

## What is the current behavior?

Current `@ApiImplicitQuery()` does not support `Enum` type. Enums on `QueryParameter` in Swagger is used quite frequently for easy to pick filter value like Gender, SortOrder, etc....

Issue Number: #101 

## What is the new behavior?
`@ApiImplicitQuery()` now takes in `enum` value (Array of values). The generated json

Usage:
1. 
```javascript
@ApiImplicitQuery({
    name: 'gender',
    enum: ['Male', 'Female']
})
```
- This will generate, in the SwaggerDoc, the following paramter:
```json
{
   type: "string",
   name: "gender",
   in: "query",
   required: true,
   enum: [
      "Male",
      "Female"
   ]
}
```
On SwaggerUI:
image

- If `isArray` property is also provided along with the `enum` property: 
```javascript
@ApiImplicitQuery(name: "role", enum: ["Admin", "Moderator", "User"], isArray: true)
```
then the generated json will look like:
```json
{
   name: "role",
   required: true,
   in: "query",
   type: "array",
   items: {
      type: "String",
      enum: [
         "Admin",
         "Moderator",
         "User"
      ]
   },
   collectionFormat: "multi"
}
```
and on SwaggerUI, the parameter will now become a `multiselect` field with the enum values:
image

```javascript
console.log(role); // for the above screenshot, ['Moderator', 'User']
```
## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by nartc** [comment]
Let me know if you want me to update the docs as well.

**Comment by kamilmysliwiec** [comment]
*Let me know if you want me to update the docs as well.*

That would be cool 🔥

**Comment by P0NE** [comment]
When do you think merge this PR ? The doc is already update but not the code. Cordially.

**Comment by P0NE** [comment]
UP

**Comment by kiwikern** [comment]
@kamilmysliwiec It seems to confuse people that the docs describe a not yet implemented feature, see [Stackoverflow](https://stackoverflow.com/q/51651493/4694994). If this cannot be merged yet, maybe the docs should be reverted until the merge? 🤷‍♂️

**Comment by kamilmysliwiec** [comment]
Thanks @nartc and sorry for the ambiguities, it was my mistake. This feature will be available in the incoming release 🔥

**Pull request merged**
