### PR TITLE
Update parameter-metadata-accessor.ts

### PR DESCRIPTION
**Pull request by Makkalay**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
image

**Comment by Makkalay** [comment]
and one question why that not work for me
```
  private validateRoutePath(path: string): string {
    if (isUndefined(path)) {
      return '';
    }
    if (Array.isArray(path)) {
      path = head(path);
    }

    // let pathWithParams = '';
    // for (const item of pathToRegexp.parse(path)) {
    //   pathWithParams += isString(item) ? item : `${item.prefix}{${item.name}}`;
    // }
```

but I need to do something like

```
    const item: any = pathToRegexp.parse(path);
    const pathWithParams = item.tokens
      .map((t: { name: any }) => (isString(t) ? t : `{${t.name}}`))
      .join('');

    return pathWithParams === '/' ? '' : addLeadingSlash(pathWithParams);
  }
  ```

**Comment by kamilmysliwiec** [comment]
> PS: Fount I updated "path-to-regexp" to "^8.0.0" from 3.0.0

You shouldn't be doing that yet. See this PR https://github.com/nestjs/swagger/pull/3199

> but I need to do something like

Why?

**Comment by Makkalay** [comment]
> > PS: Fount I updated "path-to-regexp" to "^8.0.0" from 3.0.0
> 
> You shouldn't be doing that yet. See this PR #3199
> 
> > but I need to do something like
> 
> Why?

I updated all dependencies to latest in all nestjs package what I use, a year ago.

**Comment by kamilmysliwiec** [comment]
path-to-regexp v8 isn't compatible with Nest v10

**Comment by Makkalay** [comment]
> path-to-regexp v8 isn't compatible with Nest v10

all is compatible, if make changes in all nestjs code

**Comment by Makkalay** [comment]
and is not so much code what use it
```
core/utils/middleware.util.ts:import { pathToRegexp } from 'path-to-regexp';
core/router/router-explorer.ts:import { pathToRegexp } from 'path-to-regexp';
swagger/swagger-explorer.ts:import * as pathToRegexp from 'path-to-regexp';

```

**Pull request merged**
