### PR TITLE
Add decorator to allow specification of the schema type name

### PR DESCRIPTION
**Pull request by radacovsky**
You can use @ApiSchema to set a custom schema name.
Custom schema names are not inherited.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?
Currently when creating schema for a class the class name is taken as the schema name.

Issue Number: N/A

## What is the new behavior?
A new decorator has been introduced: @ApiSchema. Using this decorator you can define custom schema name different from the class name.

e.g.
@ApiSchema({name: 'User'})
class UserDto {}

will produce a schema with name User, not UserDto.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by zroadhouse-rigup** [comment]
See my latest comment on #981 re `title` vs `name` to be consistent with the OpenAPI/JSON schema specs and the need for `description`, `externalDocs`, and `deprecated`.

**Comment by kamilmysliwiec** [comment]
Thanks! Could you create a PR to the docs as well? https://github.com/nestjs/docs.nestjs.com

**Comment by radacovsky** [comment]
Ok, will do!

**Comment by radacovsky** [comment]
@kamilmysliwiec here is the PR for documentation update
https://github.com/nestjs/docs.nestjs.com/pull/1533

**Review by nartc — APPROVED** [review]
LGTM

**Review by nartc — CHANGES_REQUESTED** [review]
Have a question on the docs PR.

**Comment by radacovsky** [comment]
@nartc I haven't noticed any question there. Can you link it here, please?

**Review by nartc — APPROVED** [review]

**Comment by andrew-itscript** [comment]
When do you plan to merge and release it ?

**Comment by anchan828** [comment]
I can't wait for merge and release it!

**Comment by Dhiraj-JC** [comment]
This PR is very helpful. When you guys are plan to merge and release it?

**Comment by zroadhouse-rigup** [comment]
Can we release this soon please? It's been ready for quite a while now. There are other useful features that can be built on top of the ApiSchema decorator once this is merged (documentation at the type level).

**Pull request closed without merging**
