### PR TITLE
feat: support class decorator in @ApiParam/@ApiQuery

### PR DESCRIPTION
**Pull request by anchan828**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

I sometimes include param in the path of @Controller. It's a pain to put ApiParam on every route method in controller.

```ts
@Controller('tests/:testId')
class TestAppController {
  @ApiParam({ name: 'testId' })
  @ApiQuery({ name: 'testQuery'})
  @Get()
  public method1(@Param('testId') testId: string, @Query('testQuery') testQuery: string) {
  }

  @ApiParam({ name: 'testId' })
  @ApiQuery({ name: 'testQuery'})
  @Get()
  public method2(@Param('testId') testId: string, @Query('testQuery') testQuery: string) {
  }
}
```

## What is the new behavior?

I would like ApiParam to support class decorator to reduce waste.

```ts
@ApiParam({ name: 'testId' }) <- new
@ApiQuery({ name: 'testQuery'}) <- new
@Controller('tests/:testId')
class TestAppController {
  @Get()
  public method1(@Param('testId') testId: string, @Query('testQuery') testQuery: string) {
  }

  @Get()
  public method2(@Param('testId') testId: string, @Query('testQuery') testQuery: string) {
  }
}
```

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

Docs PR: https://github.com/nestjs/docs.nestjs.com/pull/1917

### CODE REVIEW

**Comment by AliYusuf95** [comment]
@anchan828  I think `@ApiQuery` should do the same thing

**Comment by anchan828** [comment]
Hi @AliYusuf95, That's a good idea.

So I updated the createParamDecorator. It currently supports MethodDecorator and ClassDecorator.
https://github.com/nestjs/swagger/blob/6e5281368d849d38c10a2ae8d033d2dfbcaeb4e1/lib/decorators/helpers.ts#L99-L102

In effect, decorators that use createParamDecorator will be able to support ClassDecorator (ApiBody/ApiHeader/ApiParam/ApiQuery).
Currently, ApiHeader seems to support ClassDecorator in a different way. Maybe I should unify the implementation method... 🤔

**Comment by kamilmysliwiec** [comment]
Can you add tests that check if `@ApiParam`/`@ApiQuery` used on the class level are actually being introspected by the `SwaggerExplorer`?

**Comment by anchan828** [comment]
HI @kamilmysliwiec,

I just added tests for them to `api-param.decorator.spec.ts` and `api-query.decorator.spec.ts` (Should I have added tests to `swagger-explorer.spec.ts`?).

**Comment by kamilmysliwiec** [comment]
If you could move tests that use `SwaggerExplorer` to the `swagger.explorer.spec.ts` file that would be great!

**Comment by anchan828** [comment]
I just moved SwaggerExplorer tests to `swagger.explorer.spec.ts` file.

**Comment by dimacros** [comment]
why no acccept this feature?

**Comment by anchan828** [comment]
I close this PR. It is not a good idea to keep the old code around.
If anyone needs this feature, we should create a PR for the same and discuss it.

**Pull request closed without merging**
