### PR TITLE
file upload decorator

### PR DESCRIPTION
**Pull request by Ob-La-Di**
Hi,

I made a decorator to enable file upload in swagger.

It can be used in combination with `ApiConsumes`, like so:

```ts
  @ApiConsumes('multipart/form-data')
  @ApiImplicitFile({name: 'file', required: true, description: 'csv file containing the contacts'})
```

And it gives something like that:
file input

If you need to change anything, let me know, I'll gladly do it.

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
Hi @Ob-La-Di,
Great job! 🔥 Would you mind creating a PR to the documentation that adds this decorator?

**Comment by Ob-La-Di** [comment]
I just realized that with swagger2.0 you can't send both body and form-data in the same query. So this decorator will only work if you just send a single file. 

To be able to send other data we need to change the "in" parameter from "body" to "formData". The object type will not work either. The only solution I see would be to pass every attribute of an object as a single param.

What do you think?

**Comment by Ob-La-Di** [comment]
i updated my code to pass every attribute of an object as single param with the parameter `in` set as `formData`. I made some light tests and it works.

How do you usually test this repo? So far it's been a hassle for me. 😛

**Comment by nartc** [comment]
@Ob-La-Di would you mind sharing your contact information with me? My email is `ctran2428@gmail.com`. I have some questions regarding nest/swagger. Thanks

**Comment by kamilmysliwiec** [comment]
Hi @Ob-La-Di,
Sorry for the delay. Would you mind creating a pull request to the docs as well? Also, could you resolve conflicts that have been created due to others PRs?

**Comment by kamilmysliwiec** [comment]
Just realised that this PR is incomplete, for example, `formDataModelTransformation` doesn't exists.

**Comment by andreyradkevich** [comment]
Can I use it after installing the last version of swagger?

**Comment by kamilmysliwiec** [comment]
No, unfortunately, I couldn't merge this PR due to the issue outlined above

**Comment by Ob-La-Di** [comment]
Hello, 

Sorry about the delay. I think we are good now. 

I made a PR on nestjs/docs.nestjs.com, [here](https://github.com/nestjs/docs.nestjs.com/pull/139)

**Comment by kamilmysliwiec** [comment]
Just merged. Thanks @Ob-La-Di! 👍

**Pull request merged**
