### PR TITLE
perf: limit lodash to only used method

### PR DESCRIPTION
**Pull request by phoenix741**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: 2092

## What is the new behavior?

The goal is to reduce the bundle size of @nestjs/swagger for application that use webpack in serverless mode (https://docs.nestjs.com/faq/serverless)

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

If another PR or a future change introduce an import with the syntaxe (import { aaa } from 'lodash') the bundle size will be restaured to the maximum size.

### CODE REVIEW

**Review by micalevisk — CHANGES_REQUESTED** [review]
I believe we could revert the changes made on `package-lock.json`

**Comment by phoenix741** [comment]
done, i just revert the package-lock.json

**Comment by micalevisk** [comment]
thanks

can you run `npm run format` (but do not commit any changes on files other than the ones in this PR)

**Comment by phoenix741** [comment]
Yes.

Only the following two files are modifed, but none by me :

```diff
diff --git a/lib/swagger-ui/helpers.ts b/lib/swagger-ui/helpers.ts
index 86cdc12..84ce786 100644
--- a/lib/swagger-ui/helpers.ts
+++ b/lib/swagger-ui/helpers.ts
@@ -18,7 +18,9 @@ export function buildJSInitOptions(initOptions: SwaggerUIInitOptions) {
     2
   );
 
-  json = json.replace(new RegExp('"' + functionPlaceholder + '"', 'g'), () => fns.shift());
+  json = json.replace(new RegExp('"' + functionPlaceholder + '"', 'g'), () =>
+    fns.shift()
+  );
 
   return `let options = ${json};`;
 }
diff --git a/lib/swagger-ui/swagger-ui.ts b/lib/swagger-ui/swagger-ui.ts
index 9a9b243..e91b473 100644
--- a/lib/swagger-ui/swagger-ui.ts
+++ b/lib/swagger-ui/swagger-ui.ts
@@ -70,7 +70,9 @@ export function buildSwaggerHTML(
       customJs ? `<script src="${customJs}"></script>` : ''
     )
     .replace(
-      '<% customJsStr %>', customJsStr ? `<script> ${customJsStr} </script>` : '')
+      '<% customJsStr %>',
+      customJsStr ? `<script> ${customJsStr} </script>` : ''
+    )
     .replace(
       '<% customCssUrl %>',
       customCssUrl ? `<link href="${customCssUrl}" rel="stylesheet">` : ''

```

**Comment by phoenix741** [comment]
I don't understand why the e2e_tests failed, it doesn't seem related to my change, does it?

**Comment by mastermatt** [comment]
Is this still a concern? My understanding is the current version of Webpack and tree-shake `import { aaa } from 'lodash'` just fine.

**Comment by phoenix741** [comment]
Sorry, i just see your message. The tree-shaking feature only work when using ESM. https://webpack.js.org/guides/tree-shaking/

To work, nest should use ESM and lodash should bé replaced by lodash-es

**Pull request closed without merging**
