### PR TITLE
fix(@nestjs/swagger): remove explicitly defined params

### PR DESCRIPTION
**Pull request by arkraft**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

When defining enums with `@ApiQuery` or `@ApiParm`, their type will only be defined as `$ref` if they are not added as parameters of the method. If they are added to the method with `@Query` or `@Param`, the types will be overwritten. This behavior changed with the update 4.7.2 -> 4.7.3. Therefore i submit this as a bug fix. 

Issue Number: #1204 

## What is the new behavior?

Whether the enum is additionally defined as `@Param` or `@Query`, the result will be the same and the enum will be a reference object.

## Does this PR introduce a breaking change?
```
[x] Yes
[ ] No
```
```
@ApiQuery({ enumName: "QueryEnum", name: "test", enum: QueryEnum })
postHere(@Query("test") test: QueryEnum) {}
```

currently looks like this:

```
{
  in: "query",
  name: "test",
  schema: {
    type: "string",
    enum: [...]
  }
  ...
}
```

and it now will look like this:

```
{
  in: "query",
  name: "test",
  schema: {
    $ref: ".../QueryEnum"
  }
  ...
}
```

The second example is also the result if the method looks like this:

```
@ApiQuery({ enumName: "QueryEnum", name: "test", enum: QueryEnum })
postHere() {}
```

### CODE REVIEW

**Review by jmcdo29 — APPROVED** [review]
Lgtm. Reviewed from my phone so I may have missed something

**Comment by iamdenny** [comment]
when is this going be merged?

**Comment by arkraft** [comment]
I did not have much time to work on it lately. Now i kinda fucked up during merging and it shows that there are many changes which is not the case. Therefore i started a new PR with the fix and need to fix a test case now, hopefully this new PR will work better

**Comment by arkraft** [comment]
> when is this going be merged?

@iamdenny I created a new PR with the changes which is cleaner and i also found out, why the test was failing in the pipeline. Here is the updated PR: #1733

**Pull request closed without merging**
