### PR TITLE
Disable endpoint option

### PR DESCRIPTION
**Pull request by Ob-La-Di**
Hi,

I made another decorator to disable an endpoint, to fit my company needs. It just doesn't add the endpoint to swagger-ui for the routes with the decorator.

To use it, you juste need to add `ApiDisableEndpoint()` before a controller method.

I'm still a junior dev, so if there's any mistakes, feel free to let me know and I'll gladly correct it.

Bonus: It coincidentally resolves issue #92.

Thanks

### CODE REVIEW

**Comment by Ob-La-Di** [comment]
Changed the name of the decorator and made a PR to the documentation. 👍

**Comment by thaoula** [comment]
Hi @kamilmysliwiec,

Do you think this PR will be merged? 

Currently we are doing a bit of gymnastics with multiple nest applications to try and document only our public API using the swagger module.

Would love to just use an attribute :)

**Comment by nartc** [comment]
Though it might be a hassle but `@ApiHidden()` would be a great name also.

**Comment by kamilmysliwiec** [comment]
Amazing job, thanks @Ob-La-Di !

**Pull request merged**
