### PR TITLE
fix(swagger): @ApiHeader default type instead of overwriting

### PR DESCRIPTION
**Pull request by simonkurka**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #1653

## What is the new behavior?
string ist the default type for ApiHeader, but can be overwritten.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by simonkurka** [comment]
I think there's no docs update needed.
A test-case might be a good idea. Do you have a hint where this should reside in?
Is the commit message ok? swagger is not in the [supported scopes](https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md#commit) but this seemed to be meaningful to me.

**Comment by kamilmysliwiec** [comment]
Can you explain what other types we should support? I though header is always a string anyway

**Comment by simonkurka** [comment]
https://swagger.io/docs/specification/data-models/data-types/ lists possible types in swagger.

The case here is that the swagger type at first level is always overwritten with string, which is actually wrong as swagger supports more types.

This has nothing to do with the fact that HTTP-Headers are always strings. The case is the swagger output and as a result the swagger-ui generation which both are typed.

**Comment by kamilmysliwiec** [comment]
Can you update e2e tests with non-string headers then?

**Comment by yanavery** [comment]
@kamilmysliwiec, @simonkurka, what happened with this? Sorry to comment on a closed PR ...

We have a similar use case, although simpler, we need our header values to be of type `number` (not `string`) as they are used for data paging such as `X-Paging-Offset` and `X-Paging-Size`, but the Swagger file gets generated as follows:
```
...
"someGetMethod","parameters": [
 {
   "name":"X-Paging-Offset",
   "in":"header",
   "description":"The offset to start returning data from, starting at 0.",
   "required":false,
   "schema":{"type":"string"}
 },
 {
   "name":"X-Paging-Size",
   "in":"header",
   "description":"The number of records to return.",
   "required":false,
   "schema":{"type":"string"}
 }
],
...
```
Even though we have the following in our code (see `schema` -> `type` -> `number`):
```
// ====================================================================================================================
export function DataPaging() {
  return applyDecorators(
    ApiHeader({
      name: HEADER_DATA_PAGING_OFFSET,
      required: false,
      description: "The offset to start returning data from, starting at 0.",
      schema: { type: "number" },
    }),
    ApiHeader({
      name: HEADER_DATA_PAGING_PAGE_SIZE,
      required: false,
      description: "The number of records to return.",
      schema: { type: "number" },
    })
  );
}
```

The `"schema":{"type":"number"}` is simply ignored and it looks like the underlying code is just blindly putting `schema: { type: "string" },` which explains why this is happening ...

See https://github.com/nestjs/swagger/blob/b465c9a75dcf14b469cb420f6a6d3428d4f8e67b/lib/decorators/api-header.decorator.ts#L30

We use the generated Swagger file to then generate our Axios API client, which would be much better if properly typed instead of typed with `string` parameter values - should be `number` values:
```
/* 
 * @param {string} [xPagingOffset] The offset to start returning data from, starting at 0.
 * @param {string} [xPagingSize] The number of records to return.
 * @param {*} [options] Override http request option.
 * @throws {RequiredError}
 */
  someGetMethod: async (xPagingOffset?: string, xPagingSize?: string, options: AxiosRequestConfig = {}): 
  Promise<RequestArgs> => {
     const localVarPath = `/v1/someGetMethod`;
     ...
```

Any way this could be worked around or fixed?

Thanks!

**Comment by cityreader** [comment]
I can confirm this PR has fix my issue when I want to set type to ApiHeader schema type to `boolean`

```
  @ApiHeader({
    name: 'Add-Components',
    description: 'Specifies if the response should contain the address broken down into its components.',
    schema: {
      type: 'boolean',
      default: false,
    },
  })
```

Before

Screenshot 2023-07-13 at 3 08 53 pm

After

Screenshot 2023-07-13 at 3 07 33 pm

**Pull request closed without merging**
