### PR TITLE
Support multiple spec files

### PR DESCRIPTION
**Pull request by nartc**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

As #129 mentioned, there currently is no way to make this work.

Issue Number: #129 

## What is the new behavior?
`SwaggerModule` now supports multiple spec files to be served on different SwaggerUI Routes.

```javascript

  const swaggerDoc = SwaggerModule.createDocument(app, swaggerOptions, [SecondaryModule]);
  const swaggerDoc2 = SwaggerModule.createDocument(app, swaggerOptions, [ThirdModule]);

  SwaggerModule.setup('/api/docs', app, swaggerDoc);
  SwaggerModule.setup('/api/docs2', app, swaggerDoc2);
```

Result: 
**/api/docs**
image

**/api/docs2**
image

This PR is based on this issue here on `swagger-ui-express` (which is the package used internally to serve SwaggerUI): https://github.com/scottie1984/swagger-ui-express/issues/65

**NOTE:** The PR is built towards Modularization Approach that NestJS embraces. If you build your application where you *shove* everything on `AppModule` then this PR won't be able to help. With that being said, if there's desire to support for such approach (everything-on-app-module), I'll modify/update the PR.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```
This PR adds an **optional** `includedModules` parameter to `SwaggerModule.createDocument()`. It is not required to pass it in and leaving it empty maintains the current behavior of `SwaggerModule`

## Other information

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
Thanks @nartc 🙂

**Comment by kamilmysliwiec** [comment]
If you want, feel free to create a PR. Pay attention to the final API changes (I have comitted a one important change)

**Comment by nartc** [comment]
@kamilmysliwiec you mean for the Doc?

**Comment by kamilmysliwiec** [comment]
Yes, exactly 🙂just missed that part lol

**Comment by nartc** [comment]
Docs added: https://github.com/nestjs/docs.nestjs.com/pull/151

**Pull request merged**
