### PR TITLE
fix inputPath swagger undefined

### PR DESCRIPTION
**Pull request by martds**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by micalevisk** [comment]
in which case that `inputPath` is `undefined`?

that `validatePath` is being used here:

https://github.com/nestjs/swagger/blob/51f0eb614a650b547c4f4fcfad401d05f6092849/lib/swagger-module.ts#L46-L50

and I don't think `path` could be `undefined`

https://github.com/nestjs/swagger/blob/51f0eb614a650b547c4f4fcfad401d05f6092849/lib/swagger-module.ts#L38-L39

**Comment by micalevisk** [comment]
how your `bootstrap` function looks like?

**Comment by martds** [comment]
```
async function bootstrap() {
    const app = await NestFactory.create(AppModule, {
        bodyParser: true,
    });
    
    await swaggerConfig(app, []);

    const port = process.env.PORT || 3000;
    await app.listen(port).then(() => console.log(`Application listening on port ${port}`));
}
bootstrap();
```

**Comment by micalevisk** [comment]
what about `swaggerConfig`?

**Comment by martds** [comment]
```
import { INestApplication } from '@nestjs/common';
import { DocumentBuilder, SwaggerDocumentOptions, SwaggerModule } from '@nestjs/swagger';

const APP_VERSION = process.env.npm_package_version;

export const swaggerConfig = async function conf(app: INestApplication, modules: any[]): Promise<void> {
    const config = new DocumentBuilder()
        .setTitle(process.env.SWAGGER_TITLE)
        .setDescription(process.env.SWAGGER_DESCRIPTION)
        .setVersion(APP_VERSION)
        .setContact('hide things of company', 'hide things of company')
        .addServer(process.env.SWAGGER_SERVER)
        .addBearerAuth()
        .build();

    const options: SwaggerDocumentOptions = {
        operationIdFactory: (controllerKey: string, methodKey: string) => methodKey,
        include: modules,
    };
    const document = SwaggerModule.createDocument(app, config, options);
    SwaggerModule.setup(process.env.SWAGGER_DOCS, app, document);
};
```

**Comment by micalevisk** [comment]
alright, you got that error because `process.env.SWAGGER_DOCS` is `undefined`, and this is not allowed (check out the type def of `SwaggerModule.setup`)

So we can close this PR.

**Comment by micalevisk** [comment]
also, instead of using `process.env.` directly, I'd say is better to use some lib like `@nestjs/config`. Retrieve the `ConfigService` instance by calling `app.get(ConfigService)`, and then you could access the env. var via `configService.get('SWAGGER_DOCS')`. It won't be `undefined` anymore because `dotenv` will be loaded at that time

**Comment by martds** [comment]
ok, tks

**Pull request closed without merging**
