### PR TITLE
fix 'api/-json' url with trailing slash

### PR DESCRIPTION
**Pull request by ruscon**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ x ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

this bug is reproduced if you have express setup:
```javascript
app.set('strict routing', true);
```

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[ x ] No
```

## Other information

### CODE REVIEW

**Comment by johannesschobel** [comment]
i think, we should rename the file as well. currently it is called `FILENAME-json`, however, the official "OpenAPI Spec" suggests that the file should be called `openapi.json`

### OpenApi V3

> It is RECOMMENDED that the root OpenAPI document be named: `openapi.json` or `openapi.yaml`.

( see https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.0.md#documentStructure )

Although it is "only" a recommendation, i think we should stick to this!

### OpenApi 2

> By convention, the Swagger specification file is named `swagger.json`.

(see https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/2.0.md#file-structure )

**Comment by ruscon** [comment]
@kamilmysliwiec ping

**Comment by ssethu24** [comment]
Create PR for openapi #935 
 @kamilmysliwiec

**Comment by Borales** [comment]
Having Swagger mapped to the `/` route - makes the OpenAPI file path look ridiculous at `/-json`.

A faster option for us was adding a semi-static route right after the Swagger init:

```ts
  const swaggerSettings = new DocumentBuilder()
    .setTitle('...')....

  const swagger = SwaggerModule.createDocument(app, swaggerSettings);

  SwaggerModule.setup('/', app, swagger, {
    swaggerOptions: { persistAuthorization: true }
  });

  app.getHttpAdapter().get('/openapi.json', (req, res) => {
    res.setHeader('Content-Type', 'application/json');
    res.end(JSON.stringify(swagger));
  });
```

**Pull request closed without merging**
